//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mod3D.rc
//
#define ID_INDICATOR_X                  102
#define ID_INDICATOR_Y                  103
#define ID_INDICATOR_Z                  104
#define ID_INDICATOR_GZ                 105
#define ID_INDICATOR_M                  106
#define ID_INDICATOR_MX                 107
#define ID_INDICATOR_MY                 108
#define ID_INDICATOR_MZ                 109
#define ID_INDICATOR_ROW                110
#define ID_INDICATOR_COL                111
#define ID_SMALLSEPARATOR               112
#define ID_INDICATOR_COMP               113
#define IDD_DLGHTML_ABOUT               119
#define IDR_HTML_DLGHTMLABOUT           120
#define IDR_HTML_DLGPPBODYDRAW          121
#define IDR_HTML_DLGGRIDSELPROP         122
#define IDR_MAINFRAME                   128
#define IDR_MOD3DTYPE                   129
#define IDR_PROFTYPE                    130
#define ID_THREAD_FINISHED              131
#define ID_INDICATOR_FLD                132
#define IDR_GRIDTYPE                    133
#define IDR_TOOLBAR_MODEL               141
#define IDR_TOOLBAR_PROF_VIEW           141
#define IDD_DLG_MODEL_RANGE_Z           143
#define IDR_MENU_BODY                   146
#define IDR_MENU_FLOAT_BODY             146
#define IDD_DLG_MODEL_INSERT_EXISTING_BODY 147
#define IDD_DLG_BODY_DESCRIPTION        149
#define IDD_DLG_BODY_SELECT             152
#define IDC_CURSOR_EDGE                 155
#define IDC_CURSORZOOM                  156
#define IDC_CURSOR_ZOOM                 156
#define IDC_CURSOR_HSCROLL              157
#define IDC_CURSOR_VSCROLL              158
#define IDC_CURSOR_ZOOM_IN              160
#define IDC_CURSOR_ZOOM_OUT             161
#define IDD_DLG_BODY_CREATION           164
#define IDR_TOOLBAR_FLD_VIEW            165
#define IDD_DLG_MODEL_INDUCING_FIELD    167
#define IDD_DLG_MODEL_EDIT_BODIES       168
#define IDD_DLG_MODEL_DEF_OBS           170
#define IDR_TOOLBAR_MAP_VIEW            171
#define IDD_DLG_FIELD_IMPEXP            174
#define IDR_MENU_BODY_INS               182
#define IDR_MENU_FLOAT_BODY_LINE        182
#define IDD_DLG_BODY_IMPORT             187
#define IDD_DLG_MODEL_BODY_IMPORT       187
#define IDD_DLG_BODY_EXPORT             200
#define IDD_DLG_MODEL_IMPORT_PICTURE    204
#define IDD_DLG_OBJECT_MANAGER          205
#define ID_VIEW_EDIT_PICTURE            206
#define ID_MODEL_IMPORT_BITMAP          208
#define ID_BODY_LOCK                    209
#define ID_VIEW_REDRAW                  210
#define ID_VIEW_EQUAL_SCALE             212
#define IDD_DLG_MODEL_GUIDELINE         214
#define ID_MODEL_DIGITIZE               215
#define IDC_CURSOR_DIGITIZE             216
#define IDC_CURSOR_MAPVIEW              217
#define ID_GRIDLINES_HORIZONTAL         221
#define ID_GRIDLINES_VERTICAL           222
#define ID_VIEW_EDITCHECKMARKS          224
#define IDC_CURSOR_RESIZE               225
#define IDC_CURSOR_BODY_MOVE            228
#define ID_BODY_MOVE_VERTICAL           230
#define ID_MODEL_CONTROL                233
#define ID_VIEW_SET_VERTICAL_RANGE      234
#define ID_BODY_COPY_TO_NEXT_PROFILE    235
#define ID_BODY_COPY_TO_PREVIOUS_PROFILE 236
#define ID_BODY_FILL                    237
#define ID_BODY_ACTIVE                  238
#define ID_VIEW_FIELD_TOOLBAR_GRADIENT  243
#define IDR_3DVIEW                      267
#define IDS_3DVIEWGRID                  268
#define ID_WINDOW_NEW_GRID3D            269
#define ID_VIEW_PREVIOUS_PROFILE        272
#define ID_VIEW_NEXT_PROFILE            273
#define ID_MODEL_TXX                    281
#define ID_MODEL_TYY                    282
#define ID_MODEL_TZZ                    283
#define ID_MODEL_TXY                    284
#define ID_MODEL_TXZ                    285
#define ID_MODEL_TYZ                    286
#define ID_VIEW_MODELED_FIELD           287
#define ID_VIEW_MEASURED_FIELD          288
#define ID_VIEW_DIFFERENCE_FIELD        289
#define ID_VIEW_AXIS_FIELD              290
#define IDD_DLG_MODEL_GRD_ACTIVE        292
#define ID_COMPUTE_ACTIVE_FIELD         293
#define ID_VIEW_SETFIELDINDICATOR       294
#define IDD_DLG_MODEL_FLD_INDICATOR     295
#define IDD_DLG_VIEW_MAP                297
#define IDI_ICON_OK                     298
#define IDI_ICON_BAD                    299
#define IDD_DLG_PEN                     300
#define IDC_CURSOR_BD_LINE              304
#define IDC_CURSOR_BD                   305
#define IDC_CURSOR_LINE                 306
#define IDC_CURSOR_SB_VRT               307
#define IDC_CURSOR_PT                   308
#define IDC_CURSOR_SB_HRZ               309
#define IDC_CURSOR_NORMAL               310
#define IDC_CURSOR_DIV                  311
#define ID_BODY_REMOVE_FROM_PROFILE     312
#define ID_BODY_REMOVE                  313
#define ID_BODY_REMOVE314               314
#define ID_VIEW_FIELD_IMAGE             318
#define ID_VIEW_FIELD_CONTOURS          319
#define IDC_CURSOR_OBJECT               321
#define IDD_DLG_AXIS                    322
#define ID_COMPUTE_REAL_TIME            323
#define ID_EDIT_BITMAPS                 324
#define ID_EDIT_GUIDELINES              325
#define ID_IMPORT_MEASURED_FIELD        326
#define ID_IMPORT_BITMAP                327
#define ID_IMPORT_GUIDE_LINE            328
#define ID_EDIT_DIGITIZE                329
#define ID_MODEL_PROPERTIES             330
#define ID_IMPORT_MEASURED_FIELD2       330
#define ID_OBJECT_MANAGER               331
#define ID_MODEL_PROPERTIES2            333
#define IDD_DLG_MODEL                   334
#define ID_FILE_EXPORT                  335
#define ID_EXPORT_MODELED_FIELD         336
#define ID_EXPORT_BITMAP                337
#define ID_EXPORT_GUIDE_LINE            338
#define ID_EXPORT_BODY                  339
#define ID_IMPORT_BODY                  340
#define ID_VIEW_OBSERVATION_CONTOURS    345
#define ID_VIEW_OBSERVATION_IMAGE       346
#define ID_VIEW_SHOW_OBJECTS            347
#define ID_VIEW_OBSERVATION_POINTS      348
#define ID_VIEW_BODY_BOUNDARIES         349
#define ID_PROFILE_NEXT_SHOW            350
#define ID_PROFILE_PREVIOUS_SHOW        351
#define IDC_CURSOR_DIV_VRT              354
#define ID_VIEW_PROFILES                355
#define ID_IMPORT_GUIDELINES_MULTIPLE   356
#define IDD_OBJ_GRD                     357
#define IDB_BMP_OPEN                    358
#define ID_IMPORT_GRID                  359
#define ID_Menu                         360
#define IDI_OPEN                        362
#define IDR_MENU_OBJMNG                 364
#define ID_OBJMNG_PROPERTIES            365
#define ID_OBJMNG_DELETE                366
#define ID_PROFILE_SHOW_MODEL_GUIDELINE 367
#define IDR_MENU_FLOAT_PROF             368
#define ID_PROFILE_EXTREM               369
#define ID_PROFILEVIEW_NEXT             370
#define ID_PROFILEVIEW_PREVIOUS         371
#define ID_PROFILE_GOTONEXT             372
#define ID_PROFILE_GOTOPREVIOUS         373
#define ID_PROFILE_SET_EXTREM_FIELD     374
#define ID_PROFILE_JUMPTOEXTREM         375
#define ID_PROFILE_JUMPTOMIN            376
#define ID_PROFILE_JUMPTOMAX            377
#define IDD_DLG_FIELD_SELECT            378
#define ID_PROFILE_SAVE_CURRENT_SETTINGS 381
#define ID_PROFILE_LOAD_SETTINGS        382
#define IDD_DLG_PROFILE_SETTINGS        383
#define IDD_DLG_FIT_1D                  384
#define ID_COMPUTE_FIT_1D               386
#define IDR_MENU_FLOAT_VERTEX           387
#define ID_VERTEX_FIT                   388
#define ID_VERTEX_1DFITPROPERTIES       389
#define IDD_DLG_3DVIEW_MODEL            390
#define IDD_DLG_3DVIEW_SETTINGS         391
#define IDD_DLG_3DVIEW_FIELD            392
#define IDD_DLG_3DVIEW_AXES             393
#define IDD_DLG_3DVIEW_DRAW             394
#define IDB_BMP_VIEW3D_MAP              395
#define IDB_BMP_SN                      396
#define IDB_BITMAP1                     397
#define IDB_BMP_EW                      397
#define IDD_DLG_BODY_GRAV               398
#define IDD_DLG_BODY_MAG                399
#define IDD_DLG_BODY_COMPUTATION        400
#define IDD_DLG_BODY_DRAW               401
#define IDD_DLG_3DVIEW_SAVE_LOAD        403
#define ID_PROFILE_SHOW_TOOLTIP         404
#define ID_PROFILE_SHOW_RMS             405
#define ID_PROFILE_SHOW_DRV             406
#define ID_BODY_INVERT_DENSITY          407
#define ID_BODY_DENSITY_INVERSION_PROPERTIES 408
#define ID_COMPUTE_DENSITY_INVERSION_PROPERTIES 409
#define IDC_CURSOR_VRTX_LOCK            410
#define IDR_MENU1                       411
#define ID_VIEW_SHOWTOOLTIP             414
#define IDD_DLG_COMPUTE_COMP            415
#define IDD_DLG_COMPUTE_GRAV            416
#define IDD_DLG_COMPUTE_MAG             417
#define ID_MODEL_BLANK_GRID             418
#define IDD_DLG_OBSERVATIONS            419
#define ID_MODEL_OBSERVATION_PROPERTIES 421
#define IDD_DLG_ABOUT                   422
#define IDD_DLG_START                   423
#define IDD_DLG_DOC_INIT_FIELD          425
#define ID_IMPORT_WELL                  426
#define IDD_DLG_WELL                    427
#define IDB_WELL                        429
#define IDD_OBJECT_MANAGER              430
#define IDD_COLOR_GRAD                  431
#define IDD_GRID_SEL_PROP               433
#define ID_EDIT_FIELD_GRID              434
#define IDD_GRID_PROPERTIES             435
#define IDI_ICON_IMG_UNCHECKED          437
#define IDI_ICON_IMG_CHECKED            438
#define IDI_ICONIMG_NONE                439
#define IDI_ICON_IMG_NONE               439
#define IDR_MAPTYPE                     440
#define IDR_MOD3D                       442
#define ID_FILE_OPEN_LAST_DOCUMENT      443
#define IDD_ABOUT_TRIESTE               444
#define IDD_ABOUT_DEMO                  445
#define ID_VIEW_EXTENDRANGE             446
#define ID_BODY_MOVEBOBY                447
#define IDD_DLG_BODY_MOVE               448
#define IDC_CURSOR_3D                   449
#define ID_VIEW_PLANESIMULATOR          450
#define ID_WINDOW_NEWGRIDWINDOW         451
#define IDB_BITMAP2                     453
#define IDD_ABOUT_NAPOLI                454
#define IDB_NAPOLI                      455
#define IDB_DEMO_PIC                    456
#define ID_IMPORT_3DDATA                457
#define IDD_DATA3D                      458
#define IDB_BMP_MOD3D                   459
#define IDD_ABOUT_WIEN                  460
#define IDD_DIALOG1                     461
#define IDD_ABOUT_ROMAN                 462
#define ID_COMPUTE_ACTIVATE_GRID        463
#define IDC_ADD_PEG                     1002
#define IDC_BUTTON_GZ                   1004
#define IDC_NEWPEG_POSITION             1004
#define IDC_NEWPEG_COLOUR               1005
#define IDC_SELPEG_POSITION             1006
#define IDC_SELPEG_COLOUR               1007
#define IDC_SELPEG                      1008
#define IDC_BUTTON_GX                   1011
#define IDC_BUTTON_GY                   1012
#define IDC_DEL_PEG                     1012
#define IDC_BUTTON_MZ                   1013
#define IDC_BUTTON_MX                   1020
#define IDC_GRADIENT                    1020
#define IDC_BUTTON_MY                   1021
#define IDC_RADIO2                      1023
#define IDC_METHOD_COMBO                1023
#define IDC_RADIO5                      1024
#define IDC_RADIO8                      1025
#define IDC_BUTTON_M                    1030
#define IDC_SHOWTOOLTIPS                1031
#define IDC_BUTTON_G                    1033
#define IDC_EDIT_I_INCL                 1039
#define IDC_RADIO_JOIN                  1039
#define IDC_RADIO_UB                    1039
#define IDC_RADIO_UNITS                 1039
#define IDC_RADIO_PROF_ORIENTATION      1039
#define IDC_CHM_TYPE                    1039
#define IDC_RADIO3                      1040
#define IDC_EDIT_I_DECL                 1040
#define IDC_RADIO4                      1041
#define IDC_EDIT_I_TOT                  1041
#define IDC_EDIT_I_TOT2                 1042
#define IDC_EDIT_I_INCL2                1043
#define IDC_EDIT_I_DECL2                1044
#define IDC_EDIT_R_INCL                 1046
#define IDC_EDIT_R_DECL                 1047
#define IDC_EDIT_MIN_Z                  1047
#define IDC_EDIT_R_TOT                  1048
#define IDC_EDIT_MAX_Z                  1048
#define IDC_MIN_X                       1049
#define IDC_EDIT_SUSCEPTIBILITY         1049
#define IDC_MAX_X                       1050
#define IDC_MIN_Y                       1051
#define IDC_BUTTON_PEN                  1051
#define IDC_MAX_Y                       1052
#define IDC_BUTTON_BRUSH                1052
#define IDC_EDIT_WIDTH                  1054
#define IDC_EDIT_ID                     1057
#define IDC_EDIT_NAME                   1058
#define IDC_EDIT_DESC                   1060
#define IDC_LIST_BODIES                 1061
#define IDC_EDIT_SENSOR_HIGH            1065
#define IDC_EDIT_CREATION_FACTOR        1066
#define IDC_CHECK_CONST_TOP             1068
#define IDC_CHECK_CONST_BOT             1069
#define IDC_EDIT_CONST_TOP              1075
#define IDC_EDIT_CONST_BOT              1076
#define IDC_ADD_NEW                     1076
#define IDC_DELETE                      1077
#define IDC_PROPRTIES                   1078
#define IDC_SHOW                        1079
#define IDC_IMPORT                      1081
#define IDC_EXPORT                      1082
#define IDC_CHECK_VISIBLE               1083
#define IDC_EDIT_MIN_X                  1084
#define IDC_EDIT_MAX_X                  1085
#define IDC_EDIT_INCR_X                 1086
#define IDC_EDIT_MIN_Y                  1087
#define IDC_BUT_GZ                      1087
#define IDC_EDIT_MAX_Y                  1088
#define IDC_BUT_MX                      1088
#define IDC_EDIT_INCR_Y                 1089
#define IDC_BUT_MY                      1089
#define IDC_BUT_MZ                      1090
#define IDC_BUT_M                       1091
#define IDC_CHECK_SPHER_COMP            1092
#define IDC_BUT_GX                      1092
#define IDC_CHECK_MAG                   1093
#define IDC_BUT_GY                      1093
#define IDC_CHECK_GRV                   1094
#define IDC_BUT_GXZ                     1094
#define IDC_ROW_START                   1095
#define IDC_BUT_G                       1095
#define IDC_ROW_END                     1096
#define IDC_BUT_GXX                     1096
#define IDC_COL_START                   1097
#define IDC_BUT_GXY                     1097
#define IDC_COL_END                     1098
#define IDC_BUT_GZZ                     1098
#define IDC_BUT_ALL_ROWS                1099
#define IDC_BUT_GYY                     1099
#define IDC_BUT_GYZ                     1100
#define IDC_BUT_MXX                     1101
#define IDC_SPIN1                       1102
#define IDC_BUT_MXY                     1102
#define IDC_BUT_ALL_COLS                1103
#define IDC_BUT_MXZ                     1103
#define IDC_SPIN3                       1104
#define IDC_BUT_MZZ                     1104
#define IDC_SPIN2                       1105
#define IDC_BUT_MYY                     1105
#define IDC_SPIN4                       1106
#define IDC_BUT_MYZ                     1106
#define IDC_BUTTON_UB                   1107
#define IDC_EDIT_UB_VAL                 1108
#define IDC_BUTTON_LB                   1109
#define IDC_EDIT_LB_VAL                 1110
#define IDC_RADIO_LB                    1111
#define IDC_EDIT_UB_STR                 1114
#define IDC_EDIT_LB_STR                 1115
#define IDC_CHECK_EX_EDG                1116
#define IDC_EDIT_EXTENT                 1117
#define IDC_UNITS                       1118
#define IDC_BUT_BDY                     1130
#define IDC_BUT_TOP                     1131
#define IDC_BUT_BOT                     1132
#define IDC_EDIT_PROF                   1132
#define IDC_EDIT_ROW                    1132
#define IDC_EDIT_BOT                    1132
#define IDC_EDIT_MOTION_X               1132
#define IDC_EDIT_GRAD_HEIGHT_OVER_RELIF 1132
#define IDC_EDIT_XT                     1134
#define IDC_EDIT_XB                     1135
#define IDC_EDIT_YT                     1136
#define IDC_EDIT_YB                     1137
#define IDC_EDIT_ZT                     1138
#define IDC_EDIT1                       1139
#define IDC_EDIT_ZB                     1140
#define IDC_EDIT_DATA_MIN               1140
#define IDC__SC3D_Y                     1140
#define IDC_TREE                        1141
#define IDC__SC3D_Z                     1141
#define IDC_RADIO6                      1143
#define IDC_RADIO_PIC_TYPE              1144
#define IDC_RADIO_PIC_TYPE_PRF          1145
#define IDC_RADIO_PIC_TYPE_OTHHER       1146
#define IDC_CHECK_LOCK                  1147
#define IDC_BUT_DEL                     1153
#define IDC_BUT_PROP                    1154
#define IDC_EDIT_COLUMN                 1155
#define IDC_EDIT_X                      1156
#define IDC_EDIT_Y                      1157
#define IDC_EDIT_z                      1158
#define IDC_EDIT_DESCRIPTION            1159
#define IDC_CHECK_TEXT                  1161
#define IDC_CHECK_HRZ                   1164
#define IDC_CHECK_VRT                   1165
#define IDC_EDIT_STEP                   1166
#define IDC_EDIT_TOP                    1167
#define IDC_EDIT_DENSITY                1168
#define IDC_EDIT_GRD_X                  1169
#define IDC_EDIT_GRD_Y                  1170
#define IDC_EDIT_GRD_Z                  1171
#define IDC_EDIT_DO_X                   1172
#define IDC_EDIT_DO_Y                   1173
#define IDC_EDIT_DO_Z                   1174
#define IDC_CHECK_MOVE_TOP              1175
#define IDC_CHECK_MOVE_BOT              1176
#define IDC_CHECK_FIX_RELIEF            1177
#define IDC_CHECK_FIX_BOTTOM            1178
#define IDC_CHECK_MOVE_PROFILE          1179
#define IDC_EDIT_SC                     1180
#define IDC_CHECK_FILLED                1181
#define IDC_CHECK_ACTIVE                1182
#define IDC_RADIO7                      1183
#define IDC_RADIO_PROJECTION            1186
#define IDC_RADIO9                      1187
#define IDC_RADIO_SHADEMODEL            1188
#define IDC_RADIO11                     1189
#define IDC_EDIT_MOTION_Y               1190
#define IDC_EDIT_MOTION_Z               1191
#define IDC_EDIT_ROTATION_X             1193
#define IDC_EDIT_ROTATION_Y             1194
#define IDC_SPIN_ROTATION_Y             1195
#define IDC_EDIT_ROTATION_X2            1195
#define IDC_EDIT_ROTATION_Z             1196
#define IDC_SPIN6                       1197
#define IDC_SPIN_ROTATION_Z             1197
#define IDC_EDIT_ROTATION_Y2            1197
#define IDC_SPIN_MOTION_X               1198
#define IDC_EDIT_ROTATION_Z2            1198
#define IDC_SPIN_MOTION_Y               1199
#define IDC_SPIN_MOTION_Z               1200
#define IDC_SPIN_ROTATION_X             1201
#define IDC_SPIN_ROW_START              1202
#define IDC_EDIT_ROTATION_X3            1202
#define IDC_SPIN_ROW_END                1203
#define IDC_EDIT_ROTATION_Y3            1203
#define IDC_SPIN_COL_START              1204
#define IDC_EDIT_ROTATION_Z3            1204
#define IDC_SPIN_COL_END                1205
#define IDC_CHECK_VIRTUAL               1206
#define IDC_EDIT_LINE_WIDTH             1207
#define IDC_RADIO_GRAD_HEIGHT           1217
#define IDC_EDIT_GRAD_HEIGHT            1218
#define IDC_RADIO_GRAD_HEIGHT_OVER_RELIEF 1219
#define IDC_COMBO1                      1220
#define IDC_RADIO_COMP_TYPE             1221
#define IDC_CHECK_GRV_TENS              1222
#define IDC_FLD_GX                      1224
#define IDC_RADIO_FLD_TYPE              1225
#define IDC_FLD_GY                      1225
#define IDC_FLD_GZ                      1226
#define IDC_FLD_G                       1227
#define IDC_FLD_GXX                     1228
#define IDC_FLD_GYY                     1229
#define IDC_FLD_GZZ                     1230
#define IDC_FLD_GXY                     1231
#define IDC_FLD_GXZ                     1232
#define IDC_FLD_GYZ                     1233
#define IDC_FLD_MX                      1234
#define IDC_FLD_MY                      1235
#define IDC_FLD_MZ                      1236
#define IDC_FLD_M                       1237
#define IDC_FLD_MXX                     1238
#define IDC_FLD_MYY                     1239
#define IDC_FLD_MZZ                     1240
#define IDC_FLD_MXY                     1241
#define IDC_FLD_MXZ                     1242
#define IDC_FLD_MYZ                     1243
#define IDC_FLD_DGX                     1244
#define IDC_FLD_DGY                     1245
#define IDC_FLD_DGZ                     1246
#define IDC_FLD_DG                      1247
#define IDC_FLD_DGXX                    1248
#define IDC_FLD_DGYY                    1249
#define IDC_FLD_DGZZ                    1250
#define IDC_FLD_DGXY                    1251
#define IDC_FLD_DGXZ                    1252
#define IDC_FLD_DGYZ                    1253
#define IDC_FLD_DMX                     1254
#define IDC_FLD_DMY                     1255
#define IDC_FLD_DMZ                     1256
#define IDC_FLD_DM                      1257
#define IDC_FLD_DMXX                    1258
#define IDC_FLD_DMYY                    1259
#define IDC_FLD_DMZZ                    1260
#define IDC_FLD_DMXY                    1261
#define IDC_FLD_DMXZ                    1262
#define IDC_FLD_DMYZ                    1263
#define IDC_FLD_MGX                     1264
#define IDC_FLD_MGY                     1265
#define IDC_FLD_MGZ                     1266
#define IDC_FLD_MG                      1267
#define IDC_FLD_MGXX                    1268
#define IDC_FLD_MGYY                    1269
#define IDC_FLD_MGZZ                    1270
#define IDC_FLD_MGXY                    1271
#define IDC_FLD_MGXZ                    1272
#define IDC_FLD_MGYZ                    1273
#define IDC_FLD_MMX                     1274
#define IDC_FLD_MMY                     1275
#define IDC_FLD_MMZ                     1276
#define IDC_FLD_MM                      1277
#define IDC_FLD_MMXX                    1278
#define IDC_FLD_MMYY                    1279
#define IDC_FLD_MMZZ                    1280
#define IDC_FLD_MMXY                    1281
#define IDC_FLD_MMXZ                    1282
#define IDC_FLD_MMYZ                    1283
#define IDC_COMBO_FLD_INDICATOR         1286
#define IDC_CHECK_OBSERVATION_POINTS    1287
#define IDC_CHECK_OBS_POINTS            1287
#define IDC_CHECK_RELIEF_CONTOURS       1288
#define IDC_CHECK_OBS_CONTOURS          1288
#define IDC_CHECK_RELIEF_BITMAP         1289
#define IDC_CHECK_OBS_BITMAP            1289
#define IDC_CHECK_IMPORTED_BITMAPS      1290
#define IDC_CHECK_OBJECTS               1290
#define IDC_CHECK_EQUAL_SCALE           1291
#define IDC_CHECK_SCALE_EQUAL           1291
#define IDC_RADIO_IMAGE_QUALITY         1292
#define IDC_CHECK_HORIZONTAL_GRID       1293
#define IDC_CHECK_GRID_HRZ              1293
#define IDC_CHECK_VERICAL_GRID          1294
#define IDC_CHECK_OUTFCT                1294
#define IDC_CHECK_GRD_VRT               1294
#define IDC_CHECK_HORIZONTAL            1295
#define IDC_EDIT_OPACITY                1296
#define IDC_CHECK_SHOW_ROW              1297
#define IDC_CHECK_SHOW_COL              1298
#define IDC_EDIT_FILE_PATH              1299
#define IDC_BUTTON_BROWSE               1300
#define IDC_BUTTON_COLOR                1304
#define IDC_COMBO_STYLE                 1305
#define IDC_SPIN_WIDTH                  1306
#define IDC_BUTTON1                     1307
#define IDC_BUTTON_LINE_GRDPT           1307
#define IDC_BROWSE                      1307
#define IDC_BUTTON_SAVE                 1307
#define IDC_BUTTON_PROCEED              1307
#define IDC_BUT_SN                      1307
#define IDC_BUT_LOG_BROWSE              1307
#define IDC_BUTTON_BLANK                1307
#define IDC_BUT_CREATE                  1307
#define IDC_SAVE                        1307
#define IDC_GTF_FROM_GRID               1307
#define IDC_BUT_NS                      1308
#define IDC_BUTTON3                     1309
#define IDC_BUTTON_LINE_PRFSEL          1309
#define IDC_BUTTON_REMOVE               1309
#define IDC_BUT_EW                      1309
#define IDC_BUT_PROCEED                 1309
#define IDC_COLORBUT                    1309
#define IDC_BUTTON4                     1310
#define IDC_BUTTON_REMOVE_ALL           1310
#define IDC_BUT_WE                      1310
#define IDC_BUTTON5                     1311
#define IDC_BUTTON_LINE_PRF             1311
#define IDC_BUTTON_APPLY                1311
#define IDC_BUT_MAP                     1311
#define IDC_BUTTON6                     1312
#define IDC_BUTTON_FONT_PRF             1312
#define IDC_EDIT2                       1313
#define IDC_BUTTON_FONT_PRFSEL          1313
#define IDC_NAME                        1313
#define IDC_EDIT_TOL                    1313
#define IDC_EDIT_DUMMY_MAX              1313
#define IDC_EDIT_SENSOR_CONST           1313
#define IDC_DRAW_WIDTH                  1313
#define IDC_MIN                         1313
#define IDC_EDIT_DATA_MAX               1314
#define IDC_RADIO_TYPE                  1315
#define IDC_DRAW_WIDTH_3D               1315
#define IDC_CHECK_AUTOMATIC_TL          1316
#define IDC_EDIT_MAJOR_NUMBER           1317
#define IDC_EDIT_MAJOR_START            1318
#define IDC_EDIT_MAJOR_INCREMENT        1319
#define IDC_EDIT_MINOR_DECIMALS         1320
#define IDC_CHECK_MAJOR_TICK            1321
#define IDC_CHECK_MAJOR_LABEL           1322
#define IDC_CHECK_MINOR_TICK            1323
#define IDC_CHECK_MINOR_LABEL           1324
#define IDC_EDIT_MAJOR_DECIMALS         1325
#define IDC_EDIT_DATALMITS_MIN          1326
#define IDC_EDITDATALIMITS_MAX          1327
#define IDC_BUTTON_FONT_MINOR           1328
#define IDC_CHECK_EXTEND_BOUNDARIES     1329
#define IDC_BUTTON_FONT_MAJOR_LBL       1330
#define IDC_EDIT_EXTEND_EAST            1330
#define IDC_EDIT_EXTEND_WEST            1331
#define IDC_RADIO_CREATION              1334
#define IDC_EDIT_EXTEND_NORTH           1335
#define IDC_EDIT_EXTEND_SOUTH           1336
#define IDC_BUTTON_PEN_PREV             1338
#define IDC_BUTTON_PEN_NEXT             1339
#define IDC_COMBO_BRUSH                 1340
#define IDC_COMBO_BRUSH_STYLE           1341
#define IDC_CHECK_GL_MAJOR              1342
#define IDC_SLIDER_IMG_QUALITY          1343
#define IDC_CHECK3                      1344
#define IDC_CHECK_GL_MINOR              1344
#define IDC_CHECK_PROFILES              1344
#define IDC_CHECK_GRD_DWN_X             1344
#define IDC_CHECK2                      1345
#define IDC_CHECK_BODIES                1345
#define IDC_CHECK_PROFILE_PLANES        1345
#define IDC_CHECK_TRASPARENT            1345
#define IDC_MOVEBOT                     1345
#define IDC_CUSTOM_ENABLE               1345
#define IDC_D3D_COLORDITRIBUTIN         1345
#define IDC_CHECK_LEADING_HRZ           1346
#define IDC_FILE_NAME                   1348
#define IDC_STR_ID                      1349
#define IDC_PEN                         1350
#define IDC_CHECK_TRANSPARENT_BODIES    1351
#define IDC_CHECK_DRAW_BITMAPS          1352
#define IDC_EDIT_TRANSPARENCY           1353
#define IDC_SPIN_ALPHA_BODY             1354
#define IDC_EDIT_TRANSPARENCY_BMP       1355
#define IDC_SPIN_ALPHA_BMP              1356
#define IDC_EDIT_TRANSPARENCY_PROF      1357
#define IDC_SPIN_ALPHA_PROF             1358
#define IDC_CHECK_RELIEF                1359
#define IDC_EDIT_ALPHA_REL              1360
#define IDC_SPIN_ALPHA_REL              1361
#define IDC_CHECK_FIELD                 1362
#define IDC_EDIT_ALPHA_LEADHRZ          1362
#define IDC_EDIT_ALPHA_FIELD            1363
#define IDC_SPIN_ALPHA_LEADHRZ          1363
#define IDC_SPIN_ALPHA_FLD              1364
#define IDC_RADIO1                      1365
#define IDC_CHECK_SRF_SOLID             1366
#define IDC_CHECK_SOLID_RELIEF          1367
#define IDC_CHECK_SOLID_BODY            1368
#define IDC_CHECK_SOLID_LEADHRZ         1368
#define IDC_CHECK_SOLID_RELIEF3         1369
#define IDC_EDIT_ALPHA                  1370
#define IDC_SPIN_ALPHA                  1371
#define IDC_RADIO_AXIS_LABELS           1372
#define IDC_CHECK_GRD_UP_X              1373
#define IDC_CHECK_GRD_UP_Y              1374
#define IDC_CHECK_GRD_DWN_Y             1375
#define IDC_CHECK6                      1376
#define IDC_CHECK_GRD_LINE_VRT          1376
#define IDC_CHECK_VISIBLE_3D            1377
#define IDC_COMBO_FLD                   1378
#define IDC_LIST                        1380
#define IDC_BUTTON_LOAD                 1381
#define IDC_RADIO_EXPIMP                1382
#define IDC_EDIT_BRAK_EPS               1383
#define IDC_RADIO_FIT                   1385
#define IDC_CHECK_LOG_FILE              1386
#define IDC_RADIO_MODE                  1387
#define IDC_EDIT_PROJ_ANGLE             1388
#define IDC_CHECK_TRANSPARENT_MODEL     1389
#define IDC_EDIT_SEL_SENSITIVITY        1389
#define IDC_CHECK_SOLID_MODEL           1390
#define IDC_CHECK_VRT_FACETS            1391
#define IDC_EDIT_ALPHA_PROF             1392
#define IDC_EDIT_SEL_SENSITIVITY2       1392
#define IDC_CHECK_CULL_FACET            1393
#define IDC_RADIO_CULL_FACE             1394
#define IDC_CHECK_DARKEN_INSIDE         1395
#define IDC_EDIT_DARKEN_INSIDE          1396
#define IDC_RADIO_METHOD                1397
#define IDC_EDIT_ITER                   1398
#define IDC_CHECK_AUTO_BRACKET          1399
#define IDC_EDIT_AUTO_BRACKET           1400
#define IDC_CHECK1                      1401
#define IDC_HST_EQ                      1401
#define IDC_CHECK_SOLID_3D              1401
#define IDC_MOVETOP                     1401
#define IDC_EDIT_TENS_UNITS             1402
#define IDC_EDIT_GRAV_SENSOR_HIGH       1403
#define IDC_EDIT_MAG_SENSOR_HIGH        1404
#define IDC_EDIT_LOG                    1405
#define IDC_EDIT_DUMMY_MIN              1406
#define IDC_EDIT_LB_CONST               1407
#define IDC_EDIT4                       1408
#define IDC_EDIT_UB_CONST               1408
#define IDC_MIN_Z                       1408
#define IDC_SAMPLING_RING               1408
#define IDC_D3D_MINDATA                 1408
#define IDC_EDIT_UNITS_MAG              1409
#define IDC_EDIT_GRD_ELEV_FILE          1410
#define IDC_RADIO_FIELD                 1411
#define IDC_RADIO_OBS_TYPE              1412
#define IDC_EDIT_BLANK_FILE             1413
#define IDC_EDIT_SENSOR_HEIGHT          1414
#define IDC_BUT_CLOSE                   1418
#define IDC_LIST_LITHOLOGY              1424
#define IDC_LIST_WELL                   1425
#define IDC_CS_X                        1429
#define IDC_MAX_Z                       1431
#define IDC_CS_Y                        1432
#define IDC_FILE_PATH                   1434
#define IDC_COLOR_TABLE                 1435
#define IDC_LOAD                        1441
#define IDC_GRID                        1442
#define IDC_LIST_DRAW_CHAN              1444
#define IDC_COMBO_DRAW_SIDE             1445
#define IDC_RADIUS                      1446
#define IDC_RADIUS_LOG_3D               1447
#define IDC_RADIUS_LOG                  1448
#define IDC_LOG_SAMPLING                1449
#define IDC_PIE_START                   1450
#define IDC_GRID_FILE                   1450
#define IDC_PIE_END                     1451
#define IDC_SRF_TYPE                    1451
#define IDC_SHIFT_BODY_TOP              1452
#define IDC_SHIFT_BODY_BOT              1453
#define IDC_MOVE_TAG                    1454
#define IDC_VALUE                       1455
#define IDC_ALPHA_FLD                   1456
#define IDC_ALPHA_REL                   1457
#define IDC_CUSTOM_MAX                  1457
#define IDC_CUSTOM_MIN                  1458
#define IDC_SC3D_X                      1459
#define IDC_MAX                         1460
#define IDC_D3D_COLORGRAD               1461
#define IDC_NAME_D3D                    1462
#define IDC_D3D_MAXDATA                 1463
#define IDC_D3D_SYMBOLR                 1464
#define IDC_3D_DRAW_BOTTOM              1465
#define IDC_CHECK4                      1466
#define IDC_D3D_PTS                     1466
#define IDC_D3D_SLICES                  1467
#define IDC_EDIT3                       1468
#define IDC_D3D_STACKS                  1468
#define IDC_MAG_REM_MEAN                1469
#define IDC_TNS_REM_MEAN                1470
#define IDC_GRV_REM_MEAN                1471
#define ID_COMPUTE_COMPUTE              32775
#define ID_GRID_DEFINE_PROF             32776
#define ID_GRID_DEFINE_PROF_EW          32777
#define ID_COMPUTE_COMPUTE2             32778
#define ID_GRID_DEFINE_PROF_NS          32790
#define ID_WINDOW_MAP                   32791
#define ID_MOVE_PROFILE_WEST            32793
#define ID_ID_MOVE_PROFILE_OST          32795
#define ID_MOVE_PROFILE_NORTH           32796
#define ID_MOVE_PROFILE_SOUTH           32797
#define ID_MOVE_PROFILE_OST             32798
#define ID_VIEW_ROW_PROFILE             32799
#define ID_PROFILE_EW                   32799
#define ID_VIEW_COLUMNP_ROFILE          32800
#define ID_PROFILE_SN                   32800
#define ID_WINDOW_3D                    32801
#define ID_MODEL_DEFINE_OBSERVATION     32813
#define ID_BODY_NEW_BODY                32815
#define ID_MODEL_IMPORT_OBSERVATION     32816
#define ID_COPY_PREVIOUS_PROFILE        32819
#define ID_COPY_NEXT_PROFILE            32820
#define ID_DELETE_PROFILE               32824
#define ID_ERASE_PROFILE                32825
#define ID_BODY_INSERT_NEW              32827
#define ID_BODY_INSERT_EXISTING         32828
#define ID_BODY_PROPERTIES              32829
#define ID_BODY_SELECT                  32830
#define ID_BODY_SHOW                    32832
#define ID_MODEL_PROPERTIES_GY          32835
#define ID_MODEL_PROPERTIES_GZ          32836
#define ID_MODEL_PROPERTIES_MX          32837
#define ID_MODEL_PROPERTIES_MY          32838
#define ID_MODEL_PROPERTIES_MZ          32839
#define ID_MODEL_PROPERTIES_M           32840
#define ID_MODEL_PROPERTIES_G           32841
#define ID_MODEL_PROPERTIES_DYNAMIC_COMPUTING 32842
#define ID_MODEL_PROPERTIES_GX          32843
#define ID_VIEW_MODEL_TOOLBAR           32844
#define ID_VIEW_FIELD_TOOLBAR           32845
#define ID_VIEW_ZOOM                    32848
#define ID_VIEW_ZOOM_PAGE               32849
#define ID_VIEW_ZOOM_IN                 32851
#define ID_VIEW_ZOOM_OUT                32852
#define ID_VIEW_MAP_GEOLOGY             32860
#define ID_VIEW_MAP_TOPO_CONTOUR        32861
#define ID_VIEW_MAP_OBSERVATIONS        32862
#define ID_MODEL_BODY_CREATION_PROPERTIES 32866
#define ID_VIEW_PROF_GRID               32871
#define ID_VIEW_PROF_NEXT_PROFILE       32872
#define ID_VIEW_PROF_PREV_PROFILE       32874
#define ID_VIEW_PREV_PROFILE            32874
#define ID_VIEW_PROFILE_TOOLBAR         32875
#define ID_MODEL_INDUCING_FIELD         32876
#define ID_BODY_IMPORT                  32877
#define ID_BODY_EXPORT                  32878
#define ID_BODY_EDIT                    32879
#define ID_BODY_COPY_PROFILE            32880
#define ID_MODEL_CHANGE_VERTICAL_RANGE  32881
#define ID_MODEL_EXPORTFIELD            32882
#define ID_MODEL_EXPORT_FIELD           32883
#define ID_BUT_FLD_CONTUR_GX            32885
#define ID_VIEW_MAP_FLD_CONTUR_GY       32886
#define ID_VIEW_MAP_FLD_CONTUR_GZ       32887
#define ID_VIEW_MAP_FLD_CONTUR_G        32888
#define ID_VIEW_MAP_FLD_CONTUR_MX       32889
#define ID_VIEW_MAP_FLD_CONTUR_MY       32890
#define ID_VIEW_MAP_FLD_CONTUR_MZ       32891
#define ID_VIEW_MAP_FLD_CONTUR_M        32892
#define ID_VIEW_CONTOURTOOLBAR          32896
#define ID_VIEW_TOOLBAR_MAP_VIEW        32897
#define ID_BUT_PROF_VIEW_FLD_GX         32898
#define ID_BUT_PROF_VIEW_FLD_GY         32899
#define ID_BUT_PROF_VIEW_FLD_GZ         32900
#define ID_BUT_PROF_VIEW_FLD_G          32901
#define ID_BUT_PROF_VIEW_FLD_M          32902
#define ID_BUT_PROF_VIEW_FLD_MZ         32904
#define ID_BUT_PROF_VIEW_FLD_MY         32907
#define ID_VIEW_MAP_FLD_CONTUR_GX       32912
#define ID_MODEL_IMPORTMEASUREDFIELD    32916
#define ID_MODEL_IMPORT_MEASURED_FIELD  32917
#define ID_VIEW_MOD_FLD_GX              32923
#define ID_VIEW_FIELD_MODEL_GX          32928
#define ID_VIEW_FIELD_MODEL_GY          32929
#define ID_VIEW_FIELD_MODEL_GZ          32930
#define ID_VIEW_FIELD_MODEL_G           32931
#define ID_VIEW_FIELD_MODEL_MX          32932
#define ID_VIEW_FIELD_MODEL_MY          32933
#define ID_VIEW_FIELD_MODEL_MZ          32934
#define ID_VIEW_FIELD_MODEL_M           32935
#define ID_VIEW_FIELD_MEASURED_GZ       32936
#define ID_VIEW_FIELD_MEASURED_MX       32937
#define ID_VIEW_FIELD_MEASURED_MY       32938
#define ID_VIEW_FIELD_MEASURED_MZ       32939
#define ID_VIEW_FIELD_MEASURED_M        32940
#define ID_VIEW_FIELD_SCALE_GX          32946
#define ID_VIEW_FIELD_SCALE_GY          32947
#define ID_VIEW_FIELD_SCALE_GZ          32948
#define ID_VIEW_FIELD_SCALE_G           32949
#define ID_VIEW_FIELD_SCALE_MX          32950
#define ID_VIEW_FIELD_SCALE_MY          32951
#define ID_VIEW_FIELD_SCALE_MZ          32952
#define ID_VIEW_FIELD_SCALE_M           32953
#define ID_VIEW_FIELD_SCALE_TOOLBAR     32961
#define ID_COMPUTE_PROPERTIES           32976
#define ID_VIEW_FIELD_BMP_MEASURED_M    32990
#define ID_VIEW_FIELD_CONTOUR           32991
#define ID_VIEW_MAP_TOPO_BMP            32993
#define ID_VIEW_FIELD_BMP               32996
#define ID_VIEW_PROF_VGRID              32998
#define ID_VIEW_PROF_HGRID              32999
#define ID_MOVE_PROFILE_NEXT            33011
#define ID_MOVE_PROFILE_PREV            33012
#define ID_VIEW                         33015
#define ID_BUTTON33044                  33044
#define ID_WINDOW_TILE_HORZ2            57655
#define ID_WINDOW_TILE_VERT2            57656

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        464
#define _APS_NEXT_COMMAND_VALUE         33045
#define _APS_NEXT_CONTROL_VALUE         1472
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
