 
// Commands (ID_* and IDM_*) 
#define HID_INDICATOR_X                         0x10066
#define HID_INDICATOR_Y                         0x10067
#define HID_INDICATOR_Z                         0x10068
#define HID_INDICATOR_GZ                        0x10069
#define HID_INDICATOR_M                         0x1006A
#define HID_INDICATOR_MX                        0x1006B
#define HID_INDICATOR_MY                        0x1006C
#define HID_INDICATOR_MZ                        0x1006D
#define HID_INDICATOR_ROW                       0x1006E
#define HID_INDICATOR_COL                       0x1006F
#define HID_SMALLSEPARATOR                      0x10070
#define HID_INDICATOR_COMP                      0x10071
#define HID_THREAD_FINISHED                     0x10083
#define HID_INDICATOR_FLD                       0x10084
#define HID_VIEW_EDIT_PICTURE                   0x100CE
#define HID_MODEL_IMPORT_BITMAP                 0x100D0
#define HID_BODY_LOCK                           0x100D1
#define HID_VIEW_REDRAW                         0x100D2
#define HID_VIEW_EQUAL_SCALE                    0x100D4
#define HID_MODEL_DIGITIZE                      0x100D7
#define HID_GRIDLINES_HORIZONTAL                0x100DD
#define HID_GRIDLINES_VERTICAL                  0x100DE
#define HID_VIEW_EDITCHECKMARKS                 0x100E0
#define HID_BODY_MOVE_VERTICAL                  0x100E6
#define HID_MODEL_CONTROL                       0x100E9
#define HID_VIEW_SET_VERTICAL_RANGE             0x100EA
#define HID_BODY_COPY_TO_NEXT_PROFILE           0x100EB
#define HID_BODY_COPY_TO_PREVIOUS_PROFILE       0x100EC
#define HID_BODY_FILL                           0x100ED
#define HID_BODY_ACTIVE                         0x100EE
#define HID_VIEW_FIELD_TOOLBAR_GRADIENT         0x100F3
#define HID_WINDOW_NEW_GRID3D                   0x1010D
#define HID_VIEW_PREVIOUS_PROFILE               0x10110
#define HID_VIEW_NEXT_PROFILE                   0x10111
#define HID_MODEL_TXX                           0x10119
#define HID_MODEL_TYY                           0x1011A
#define HID_MODEL_TZZ                           0x1011B
#define HID_MODEL_TXY                           0x1011C
#define HID_MODEL_TXZ                           0x1011D
#define HID_MODEL_TYZ                           0x1011E
#define HID_VIEW_MODELED_FIELD                  0x1011F
#define HID_VIEW_MEASURED_FIELD                 0x10120
#define HID_VIEW_DIFFERENCE_FIELD               0x10121
#define HID_VIEW_AXIS_FIELD                     0x10122
#define HID_COMPUTE_ACTIVE_FIELD                0x10125
#define HID_VIEW_SETFIELDINDICATOR              0x10126
#define HID_BODY_REMOVE_FROM_PROFILE            0x10138
#define HID_BODY_REMOVE                         0x10139
#define HID_BODY_REMOVE314                      0x1013A
#define HID_VIEW_FIELD_IMAGE                    0x1013E
#define HID_VIEW_FIELD_CONTOURS                 0x1013F
#define HID_COMPUTE_REAL_TIME                   0x10143
#define HID_EDIT_BITMAPS                        0x10144
#define HID_EDIT_GUIDELINES                     0x10145
#define HID_IMPORT_MEASURED_FIELD               0x10146
#define HID_IMPORT_BITMAP                       0x10147
#define HID_IMPORT_GUIDE_LINE                   0x10148
#define HID_EDIT_DIGITIZE                       0x10149
#define HID_MODEL_PROPERTIES                    0x1014A
#define HID_IMPORT_MEASURED_FIELD2              0x1014A
#define HID_OBJECT_MANAGER                      0x1014B
#define HID_MODEL_PROPERTIES2                   0x1014D
#define HID_FILE_EXPORT                         0x1014F
#define HID_EXPORT_MODELED_FIELD                0x10150
#define HID_EXPORT_BITMAP                       0x10151
#define HID_EXPORT_GUIDE_LINE                   0x10152
#define HID_EXPORT_BODY                         0x10153
#define HID_IMPORT_BODY                         0x10154
#define HID_VIEW_OBSERVATION_CONTOURS           0x10159
#define HID_VIEW_OBSERVATION_IMAGE              0x1015A
#define HID_VIEW_SHOW_OBJECTS                   0x1015B
#define HID_VIEW_OBSERVATION_POINTS             0x1015C
#define HID_VIEW_BODY_BOUNDARIES                0x1015D
#define HID_PROFILE_NEXT_SHOW                   0x1015E
#define HID_PROFILE_PREVIOUS_SHOW               0x1015F
#define HID_VIEW_PROFILES                       0x10163
#define HID_IMPORT_GUIDELINES_MULTIPLE          0x10164
#define HID_IMPORT_GRID                         0x10167
#define HID_Menu                                0x10168
#define HID_OBJMNG_PROPERTIES                   0x1016D
#define HID_OBJMNG_DELETE                       0x1016E
#define HID_PROFILE_SHOW_MODEL_GUIDELINE        0x1016F
#define HID_PROFILE_EXTREM                      0x10171
#define HID_PROFILEVIEW_NEXT                    0x10172
#define HID_PROFILEVIEW_PREVIOUS                0x10173
#define HID_PROFILE_GOTONEXT                    0x10174
#define HID_PROFILE_GOTOPREVIOUS                0x10175
#define HID_PROFILE_SET_EXTREM_FIELD            0x10176
#define HID_PROFILE_JUMPTOEXTREM                0x10177
#define HID_PROFILE_JUMPTOMIN                   0x10178
#define HID_PROFILE_JUMPTOMAX                   0x10179
#define HID_PROFILE_SAVE_CURRENT_SETTINGS       0x1017D
#define HID_PROFILE_LOAD_SETTINGS               0x1017E
#define HID_COMPUTE_FIT_1D                      0x10182
#define HID_VERTEX_FIT                          0x10184
#define HID_VERTEX_1DFITPROPERTIES              0x10185
#define HID_PROFILE_SHOW_TOOLTIP                0x10194
#define HID_PROFILE_SHOW_RMS                    0x10195
#define HID_PROFILE_SHOW_DRV                    0x10196
#define HID_BODY_INVERT_DENSITY                 0x10197
#define HID_BODY_DENSITY_INVERSION_PROPERTIES   0x10198
#define HID_COMPUTE_DENSITY_INVERSION_PROPERTIES	0x10199
#define HID_VIEW_SHOWTOOLTIP                    0x1019E
#define HID_MODEL_BLANK_GRID                    0x101A2
#define HID_MODEL_OBSERVATION_PROPERTIES        0x101A5
#define HID_IMPORT_WELL                         0x101AA
#define HID_EDIT_FIELD_GRID                     0x101B2
#define HID_FILE_OPEN_LAST_DOCUMENT             0x101BB
#define HID_VIEW_EXTENDRANGE                    0x101BE
#define HID_BODY_MOVEBOBY                       0x101BF
#define HID_VIEW_PLANESIMULATOR                 0x101C2
#define HID_WINDOW_NEWGRIDWINDOW                0x101C3
#define HID_IMPORT_3DDATA                       0x101C9
#define HID_COMPUTE_ACTIVATE_GRID               0x101CF
#define HID_COMPUTE_COMPUTE                     0x18007
#define HID_GRID_DEFINE_PROF                    0x18008
#define HID_GRID_DEFINE_PROF_EW                 0x18009
#define HID_COMPUTE_COMPUTE2                    0x1800A
#define HID_GRID_DEFINE_PROF_NS                 0x18016
#define HID_WINDOW_MAP                          0x18017
#define HID_MOVE_PROFILE_WEST                   0x18019
#define HID_ID_MOVE_PROFILE_OST                 0x1801B
#define HID_MOVE_PROFILE_NORTH                  0x1801C
#define HID_MOVE_PROFILE_SOUTH                  0x1801D
#define HID_MOVE_PROFILE_OST                    0x1801E
#define HID_VIEW_ROW_PROFILE                    0x1801F
#define HID_PROFILE_EW                          0x1801F
#define HID_VIEW_COLUMNP_ROFILE                 0x18020
#define HID_PROFILE_SN                          0x18020
#define HID_WINDOW_3D                           0x18021
#define HID_MODEL_DEFINE_OBSERVATION            0x1802D
#define HID_BODY_NEW_BODY                       0x1802F
#define HID_MODEL_IMPORT_OBSERVATION            0x18030
#define HID_COPY_PREVIOUS_PROFILE               0x18033
#define HID_COPY_NEXT_PROFILE                   0x18034
#define HID_DELETE_PROFILE                      0x18038
#define HID_ERASE_PROFILE                       0x18039
#define HID_BODY_INSERT_NEW                     0x1803B
#define HID_BODY_INSERT_EXISTING                0x1803C
#define HID_BODY_PROPERTIES                     0x1803D
#define HID_BODY_SELECT                         0x1803E
#define HID_BODY_SHOW                           0x18040
#define HID_MODEL_PROPERTIES_GY                 0x18043
#define HID_MODEL_PROPERTIES_GZ                 0x18044
#define HID_MODEL_PROPERTIES_MX                 0x18045
#define HID_MODEL_PROPERTIES_MY                 0x18046
#define HID_MODEL_PROPERTIES_MZ                 0x18047
#define HID_MODEL_PROPERTIES_M                  0x18048
#define HID_MODEL_PROPERTIES_G                  0x18049
#define HID_MODEL_PROPERTIES_DYNAMIC_COMPUTING  0x1804A
#define HID_MODEL_PROPERTIES_GX                 0x1804B
#define HID_VIEW_MODEL_TOOLBAR                  0x1804C
#define HID_VIEW_FIELD_TOOLBAR                  0x1804D
#define HID_VIEW_ZOOM                           0x18050
#define HID_VIEW_ZOOM_PAGE                      0x18051
#define HID_VIEW_ZOOM_IN                        0x18053
#define HID_VIEW_ZOOM_OUT                       0x18054
#define HID_VIEW_MAP_GEOLOGY                    0x1805C
#define HID_VIEW_MAP_TOPO_CONTOUR               0x1805D
#define HID_VIEW_MAP_OBSERVATIONS               0x1805E
#define HID_MODEL_BODY_CREATION_PROPERTIES      0x18062
#define HID_VIEW_PROF_GRID                      0x18067
#define HID_VIEW_PROF_NEXT_PROFILE              0x18068
#define HID_VIEW_PROF_PREV_PROFILE              0x1806A
#define HID_VIEW_PREV_PROFILE                   0x1806A
#define HID_VIEW_PROFILE_TOOLBAR                0x1806B
#define HID_MODEL_INDUCING_FIELD                0x1806C
#define HID_BODY_IMPORT                         0x1806D
#define HID_BODY_EXPORT                         0x1806E
#define HID_BODY_EDIT                           0x1806F
#define HID_BODY_COPY_PROFILE                   0x18070
#define HID_MODEL_CHANGE_VERTICAL_RANGE         0x18071
#define HID_MODEL_EXPORTFIELD                   0x18072
#define HID_MODEL_EXPORT_FIELD                  0x18073
#define HID_BUT_FLD_CONTUR_GX                   0x18075
#define HID_VIEW_MAP_FLD_CONTUR_GY              0x18076
#define HID_VIEW_MAP_FLD_CONTUR_GZ              0x18077
#define HID_VIEW_MAP_FLD_CONTUR_G               0x18078
#define HID_VIEW_MAP_FLD_CONTUR_MX              0x18079
#define HID_VIEW_MAP_FLD_CONTUR_MY              0x1807A
#define HID_VIEW_MAP_FLD_CONTUR_MZ              0x1807B
#define HID_VIEW_MAP_FLD_CONTUR_M               0x1807C
#define HID_VIEW_CONTOURTOOLBAR                 0x18080
#define HID_VIEW_TOOLBAR_MAP_VIEW               0x18081
#define HID_BUT_PROF_VIEW_FLD_GX                0x18082
#define HID_BUT_PROF_VIEW_FLD_GY                0x18083
#define HID_BUT_PROF_VIEW_FLD_GZ                0x18084
#define HID_BUT_PROF_VIEW_FLD_G                 0x18085
#define HID_BUT_PROF_VIEW_FLD_M                 0x18086
#define HID_BUT_PROF_VIEW_FLD_MZ                0x18088
#define HID_BUT_PROF_VIEW_FLD_MY                0x1808B
#define HID_VIEW_MAP_FLD_CONTUR_GX              0x18090
#define HID_MODEL_IMPORTMEASUREDFIELD           0x18094
#define HID_MODEL_IMPORT_MEASURED_FIELD         0x18095
#define HID_VIEW_MOD_FLD_GX                     0x1809B
#define HID_VIEW_FIELD_MODEL_GX                 0x180A0
#define HID_VIEW_FIELD_MODEL_GY                 0x180A1
#define HID_VIEW_FIELD_MODEL_GZ                 0x180A2
#define HID_VIEW_FIELD_MODEL_G                  0x180A3
#define HID_VIEW_FIELD_MODEL_MX                 0x180A4
#define HID_VIEW_FIELD_MODEL_MY                 0x180A5
#define HID_VIEW_FIELD_MODEL_MZ                 0x180A6
#define HID_VIEW_FIELD_MODEL_M                  0x180A7
#define HID_VIEW_FIELD_MEASURED_GZ              0x180A8
#define HID_VIEW_FIELD_MEASURED_MX              0x180A9
#define HID_VIEW_FIELD_MEASURED_MY              0x180AA
#define HID_VIEW_FIELD_MEASURED_MZ              0x180AB
#define HID_VIEW_FIELD_MEASURED_M               0x180AC
#define HID_VIEW_FIELD_SCALE_GX                 0x180B2
#define HID_VIEW_FIELD_SCALE_GY                 0x180B3
#define HID_VIEW_FIELD_SCALE_GZ                 0x180B4
#define HID_VIEW_FIELD_SCALE_G                  0x180B5
#define HID_VIEW_FIELD_SCALE_MX                 0x180B6
#define HID_VIEW_FIELD_SCALE_MY                 0x180B7
#define HID_VIEW_FIELD_SCALE_MZ                 0x180B8
#define HID_VIEW_FIELD_SCALE_M                  0x180B9
#define HID_VIEW_FIELD_SCALE_TOOLBAR            0x180C1
#define HID_COMPUTE_PROPERTIES                  0x180D0
#define HID_VIEW_FIELD_BMP_MEASURED_M           0x180DE
#define HID_VIEW_FIELD_CONTOUR                  0x180DF
#define HID_VIEW_MAP_TOPO_BMP                   0x180E1
#define HID_VIEW_FIELD_BMP                      0x180E4
#define HID_VIEW_PROF_VGRID                     0x180E6
#define HID_VIEW_PROF_HGRID                     0x180E7
#define HID_MOVE_PROFILE_NEXT                   0x180F3
#define HID_MOVE_PROFILE_PREV                   0x180F4
#define HID_VIEW                                0x180F7
#define HID_BUTTON33044                         0x18114
#define HID_WINDOW_TILE_HORZ2                   0x1E137
#define HID_WINDOW_TILE_VERT2                   0x1E138
 
// Prompts (IDP_*) 
 
// Resources (IDR_*) 
#define HIDR_HTML_DLGHTMLABOUT                  0x20078
#define HIDR_HTML_DLGPPBODYDRAW                 0x20079
#define HIDR_HTML_DLGGRIDSELPROP                0x2007A
#define HIDR_MAINFRAME                          0x20080
#define HIDR_MOD3DTYPE                          0x20081
#define HIDR_PROFTYPE                           0x20082
#define HIDR_GRIDTYPE                           0x20085
#define HIDR_TOOLBAR_MODEL                      0x2008D
#define HIDR_TOOLBAR_PROF_VIEW                  0x2008D
#define HIDR_MENU_BODY                          0x20092
#define HIDR_MENU_FLOAT_BODY                    0x20092
#define HIDR_TOOLBAR_FLD_VIEW                   0x200A5
#define HIDR_TOOLBAR_MAP_VIEW                   0x200AB
#define HIDR_MENU_BODY_INS                      0x200B6
#define HIDR_MENU_FLOAT_BODY_LINE               0x200B6
#define HIDR_3DVIEW                             0x2010B
#define HIDR_MENU_OBJMNG                        0x2016C
#define HIDR_MENU_FLOAT_PROF                    0x20170
#define HIDR_MENU_FLOAT_VERTEX                  0x20183
#define HIDR_MENU1                              0x2019B
#define HIDR_MAPTYPE                            0x201B8
#define HIDR_MOD3D                              0x201BA
 
// Dialogs (IDD_*) 
#define HIDD_DLGHTML_ABOUT                      0x20077
#define HIDD_DLG_MODEL_RANGE_Z                  0x2008F
#define HIDD_DLG_MODEL_INSERT_EXISTING_BODY     0x20093
#define HIDD_DLG_BODY_DESCRIPTION               0x20095
#define HIDD_DLG_BODY_SELECT                    0x20098
#define HIDD_DLG_BODY_CREATION                  0x200A4
#define HIDD_DLG_MODEL_INDUCING_FIELD           0x200A7
#define HIDD_DLG_MODEL_EDIT_BODIES              0x200A8
#define HIDD_DLG_MODEL_DEF_OBS                  0x200AA
#define HIDD_DLG_FIELD_IMPEXP                   0x200AE
#define HIDD_DLG_BODY_IMPORT                    0x200BB
#define HIDD_DLG_MODEL_BODY_IMPORT              0x200BB
#define HIDD_DLG_BODY_EXPORT                    0x200C8
#define HIDD_DLG_MODEL_IMPORT_PICTURE           0x200CC
#define HIDD_DLG_OBJECT_MANAGER                 0x200CD
#define HIDD_DLG_MODEL_GUIDELINE                0x200D6
#define HIDD_DLG_MODEL_GRD_ACTIVE               0x20124
#define HIDD_DLG_MODEL_FLD_INDICATOR            0x20127
#define HIDD_DLG_VIEW_MAP                       0x20129
#define HIDD_DLG_PEN                            0x2012C
#define HIDD_DLG_AXIS                           0x20142
#define HIDD_DLG_MODEL                          0x2014E
#define HIDD_OBJ_GRD                            0x20165
#define HIDD_DLG_FIELD_SELECT                   0x2017A
#define HIDD_DLG_PROFILE_SETTINGS               0x2017F
#define HIDD_DLG_FIT_1D                         0x20180
#define HIDD_DLG_3DVIEW_MODEL                   0x20186
#define HIDD_DLG_3DVIEW_SETTINGS                0x20187
#define HIDD_DLG_3DVIEW_FIELD                   0x20188
#define HIDD_DLG_3DVIEW_AXES                    0x20189
#define HIDD_DLG_3DVIEW_DRAW                    0x2018A
#define HIDD_DLG_BODY_GRAV                      0x2018E
#define HIDD_DLG_BODY_MAG                       0x2018F
#define HIDD_DLG_BODY_COMPUTATION               0x20190
#define HIDD_DLG_BODY_DRAW                      0x20191
#define HIDD_DLG_3DVIEW_SAVE_LOAD               0x20193
#define HIDD_DLG_COMPUTE_COMP                   0x2019F
#define HIDD_DLG_COMPUTE_GRAV                   0x201A0
#define HIDD_DLG_COMPUTE_MAG                    0x201A1
#define HIDD_DLG_OBSERVATIONS                   0x201A3
#define HIDD_DLG_ABOUT                          0x201A6
#define HIDD_DLG_START                          0x201A7
#define HIDD_DLG_DOC_INIT_FIELD                 0x201A9
#define HIDD_DLG_WELL                           0x201AB
#define HIDD_OBJECT_MANAGER                     0x201AE
#define HIDD_COLOR_GRAD                         0x201AF
#define HIDD_GRID_SEL_PROP                      0x201B1
#define HIDD_GRID_PROPERTIES                    0x201B3
#define HIDD_ABOUT_TRIESTE                      0x201BC
#define HIDD_ABOUT_DEMO                         0x201BD
#define HIDD_DLG_BODY_MOVE                      0x201C0
#define HIDD_ABOUT_NAPOLI                       0x201C6
#define HIDD_DATA3D                             0x201CA
#define HIDD_ABOUT_WIEN                         0x201CC
#define HIDD_DIALOG1                            0x201CD
#define HIDD_ABOUT_ROMAN                        0x201CE
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
